<a href="https://colab.research.google.com/github/aisyashlf/Home-Credit-/blob/main/%5BCleaning_Data%5D_Home_Credit_Scorecard_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**IMPORT DATA**

In [1]:
import pandas as pd

In [2]:
df_app_train = pd.read_csv('/content/drive/MyDrive/Home Credit/application_train.csv')
df_app_test = pd.read_csv('/content/drive/MyDrive/Home Credit/application_test.csv')
df_pre_app = pd.read_csv('/content/drive/MyDrive/Home Credit/previous_application.csv')
df_credit = pd.read_csv('/content/drive/MyDrive/Home Credit/credit_card_balance.csv')
df_bureau = pd.read_csv('/content/drive/MyDrive/Home Credit/bureau.csv')
df_bureau_balance = pd.read_csv('/content/drive/MyDrive/Home Credit/bureau_balance.csv')
df_pos = pd.read_csv('/content/drive/MyDrive/Home Credit/POS_CASH_balance.csv')
df_inst = pd.read_csv('/content/drive/MyDrive/Home Credit/installments_payments.csv')
df_sample = pd.read_csv('/content/drive/MyDrive/Home Credit/sample_submission.csv')

In [3]:
df_app_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [4]:
df_app_test.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_pre_app.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [7]:
df_bureau_balance.head()

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [8]:
df_pos.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

In [9]:
df_credit.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [10]:
df_pos.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

#**DATA CLEANING**

##application_train.csv

###Data Type

In [11]:
import pandas as pd

pd.set_option('display.max_columns', None)  # tampilkan semua kolom
df_app_train.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [12]:
df_app_train.dtypes.astype(str).value_counts()

float64    65
int64      41
object     16
Name: count, dtype: int64

In [13]:
df_app_train['TARGET']=df_app_train['TARGET'].astype('category')
df_app_train['NAME_CONTRACT_TYPE']=df_app_train['NAME_CONTRACT_TYPE'].astype('category')
df_app_train['CODE_GENDER']=df_app_train['CODE_GENDER'].astype('category')
df_app_train['FLAG_OWN_CAR']=df_app_train['FLAG_OWN_CAR'].astype('category')
df_app_train['FLAG_OWN_REALTY']=df_app_train['FLAG_OWN_REALTY'].astype('category')
df_app_train['NAME_TYPE_SUITE']=df_app_train['NAME_TYPE_SUITE'].astype('category')
df_app_train['NAME_INCOME_TYPE']=df_app_train['NAME_INCOME_TYPE'].astype('category')
df_app_train['NAME_EDUCATION_TYPE']=df_app_train['NAME_EDUCATION_TYPE'].astype('category')
df_app_train['NAME_FAMILY_STATUS']=df_app_train['NAME_FAMILY_STATUS'].astype('category')
df_app_train['NAME_HOUSING_TYPE']=df_app_train['NAME_HOUSING_TYPE'].astype('category')
df_app_train['OCCUPATION_TYPE']=df_app_train['OCCUPATION_TYPE'].astype('category')
df_app_train['WEEKDAY_APPR_PROCESS_START']=df_app_train['WEEKDAY_APPR_PROCESS_START'].astype('category')
df_app_train['ORGANIZATION_TYPE']=df_app_train['ORGANIZATION_TYPE'].astype('category')
df_app_train['FONDKAPREMONT_MODE']=df_app_train['FONDKAPREMONT_MODE'].astype('category')
df_app_train['HOUSETYPE_MODE']=df_app_train['HOUSETYPE_MODE'].astype('category')
df_app_train['WALLSMATERIAL_MODE']=df_app_train['WALLSMATERIAL_MODE'].astype('category')
df_app_train['EMERGENCYSTATE_MODE']=df_app_train['EMERGENCYSTATE_MODE'].astype('category')
df_app_train['FLAG_CONT_MOBILE']=df_app_train['FLAG_CONT_MOBILE'].astype('category')
df_app_train['FLAG_EMP_PHONE']=df_app_train['FLAG_EMP_PHONE'].astype('category')
df_app_train['FLAG_WORK_PHONE']=df_app_train['FLAG_WORK_PHONE'].astype('category')
df_app_train['FLAG_PHONE']=df_app_train['FLAG_PHONE'].astype('category')
df_app_train['FLAG_EMAIL']=df_app_train['FLAG_EMAIL'].astype('category')
df_app_train['REGION_RATING_CLIENT']=df_app_train['REGION_RATING_CLIENT'].astype('category')
df_app_train['REGION_RATING_CLIENT_W_CITY']=df_app_train['REGION_RATING_CLIENT_W_CITY'].astype('category')
df_app_train['REG_REGION_NOT_LIVE_REGION']=df_app_train['REG_REGION_NOT_LIVE_REGION'].astype('category')
df_app_train['LIVE_REGION_NOT_WORK_REGION']=df_app_train['LIVE_REGION_NOT_WORK_REGION'].astype('category')
df_app_train['REG_CITY_NOT_LIVE_CITY']=df_app_train['REG_CITY_NOT_LIVE_CITY'].astype('category')
df_app_train['REG_CITY_NOT_WORK_CITY']=df_app_train['REG_CITY_NOT_WORK_CITY'].astype('category')
df_app_train['LIVE_CITY_NOT_WORK_CITY']=df_app_train['LIVE_CITY_NOT_WORK_CITY'].astype('category')
df_app_train['AMT_REQ_CREDIT_BUREAU_HOUR']=df_app_train['AMT_REQ_CREDIT_BUREAU_HOUR'].astype('category')
df_app_train['AMT_REQ_CREDIT_BUREAU_DAY']=df_app_train['AMT_REQ_CREDIT_BUREAU_DAY'].astype('category')
df_app_train['AMT_REQ_CREDIT_BUREAU_WEEK']=df_app_train['AMT_REQ_CREDIT_BUREAU_WEEK'].astype('category')
df_app_train['AMT_REQ_CREDIT_BUREAU_MON']=df_app_train['AMT_REQ_CREDIT_BUREAU_MON'].astype('category')
df_app_train['AMT_REQ_CREDIT_BUREAU_YEAR']=df_app_train['AMT_REQ_CREDIT_BUREAU_YEAR'].astype('category')

In [14]:
df_app_test.shape

(48744, 121)

###Missing Value

In [15]:
df_app_train.isnull().sum().sort_values(ascending=False)

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
                             ...
FLAG_DOCUMENT_16                 0
FLAG_DOCUMENT_15                 0
FLAG_DOCUMENT_14                 0
FLAG_DOCUMENT_20                 0
FLAG_DOCUMENT_21                 0
Length: 122, dtype: int64

In [16]:
missing_percent = (df_app_train.isnull().sum() / len(df_app_train)) * 100
missing_percent.sort_values(ascending=False)

COMMONAREA_AVG              69.872297
COMMONAREA_MODE             69.872297
COMMONAREA_MEDI             69.872297
NONLIVINGAPARTMENTS_MEDI    69.432963
NONLIVINGAPARTMENTS_MODE    69.432963
                              ...
FLAG_DOCUMENT_16             0.000000
FLAG_DOCUMENT_15             0.000000
FLAG_DOCUMENT_14             0.000000
FLAG_DOCUMENT_20             0.000000
FLAG_DOCUMENT_21             0.000000
Length: 122, dtype: float64

In [17]:
#hapus kolom yang memiliki mv lebih dari 50%
cols_to_drop = missing_percent[missing_percent > 50].index
df_app_train = df_app_train.drop(columns=cols_to_drop)

In [18]:
#mengisi mv kolom tipe float dengan median
num_cols = df_app_train.select_dtypes(include=['float']).columns
df_app_train[num_cols] = df_app_train[num_cols].fillna(df_app_train[num_cols].median())

In [19]:
#mengisi mv kolom tipe category dengan modus
for col in df_app_train.select_dtypes('category').columns:
    df_app_train[col].fillna(df_app_train[col].mode()[0], inplace=True)

/tmp/ipython-input-3304920881.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_app_train[col].fillna(df_app_train[col].mode()[0], inplace=True)

In [20]:
#validasi mv
df_app_train.isnull().sum().sort_values(ascending=False)

SK_ID_CURR                    0
TARGET                        0
NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
                             ..
AMT_REQ_CREDIT_BUREAU_DAY     0
AMT_REQ_CREDIT_BUREAU_WEEK    0
AMT_REQ_CREDIT_BUREAU_MON     0
AMT_REQ_CREDIT_BUREAU_QRT     0
AMT_REQ_CREDIT_BUREAU_YEAR    0
Length: 81, dtype: int64

###Outlier

In [21]:
#cek outlier
df_app_train.describe()

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,REG_REGION_NOT_WORK_REGION,EXT_SOURCE_2,EXT_SOURCE_3,YEARS_BEGINEXPLUATATION_AVG,FLOORSMAX_AVG,YEARS_BEGINEXPLUATATION_MODE,FLOORSMAX_MODE,YEARS_BEGINEXPLUATATION_MEDI,FLOORSMAX_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_QRT
count,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307511.000000,3.075110e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,3.075110e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000
mean,278180.518577,0.417052,1.687979e+05,5.990260e+05,27108.487841,5.383163e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,0.999997,2.152664,12.063419,0.050769,5.145034e-01,0.515695,0.979620,0.196633,0.979277,0.194641,0.979629,0.196440,0.086258,1.417523,0.142944,1.400626,0.099717,-962.858119,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.229631
std,102790.175348,0.722121,2.371231e+05,4.024908e+05,14493.461065,3.692890e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,0.001803,0.910679,3.265832,0.219526,1.908699e-01,0.174736,0.042429,0.106761,0.046270,0.105588,0.042910,0.106998,0.079110,2.398395,0.446033,2.377224,0.361735,826.807226,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.744059
min,100002.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,1.000000,0.000000,0.000000,8.173617e-08,0.000527,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,1.000000,2.000000,10.000000,0.000000,3.929737e-01,0.417100,0.981600,0.166700,0.981100,0.166700,0.981600,0.166700,0.067000,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,1.000000,2.000000,12.000000,0.000000,5.659614e-01,0.535276,0.981600,0.166700,0.981600,0.166700,0.981600,0.166700,0.068800,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,367142.500000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,1.000000,3.000000,14.000000,0.000000,6.634218e-01,0.636376,0.982100,0.166700,0.981600,0.166700,0.982100,0.166700,0.070300,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,456255.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,0.000000,1.000000,20.000000,23.000000,1.000000,8.549997e-01,0.896010,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,348.000000,34.000000,344.000000,24.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,261.000000

In [22]:
#buat fungsi deteksi outliers
def detect_outliers_iqr(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    return outliers

In [23]:
detect_outliers_iqr(df_app_train, 'AMT_INCOME_TOTAL')

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_2,EXT_SOURCE_3,YEARS_BEGINEXPLUATATION_AVG,FLOORSMAX_AVG,YEARS_BEGINEXPLUATATION_MODE,FLOORSMAX_MODE,YEARS_BEGINEXPLUATATION_MEDI,FLOORSMAX_MEDI,TOTALAREA_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.003122,-18850,-449,-4597.0,-2379,1,1,1,1,0,0,Managers,2.0,3,3,MONDAY,16,0,0,0,0,1,1,Other,0.714279,0.540654,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,2.0,0.0,2.0,0.0,-1070.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
22,100026,0,Cash loans,F,N,N,1,450000.0,497520.0,32521.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,0.020713,-11146,-4306,-114.0,-2518,1,1,0,1,0,0,Sales staff,3.0,3,2,THURSDAY,6,0,0,0,0,0,0,Self-employed,0.457143,0.358951,0.9786,0.1667,0.9786,0.1667,0.9786,0.1667,0.0696,No,0.0,0.0,0.0,0.0,-468.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
33,100039,0,Cash loans,M,Y,N,1,360000.0,733315.5,39069.0,679500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.015221,-11694,-2060,-3557.0,-3557,1,1,0,1,0,0,Drivers,3.0,2,2,THURSDAY,10,0,0,0,1,1,0,Self-employed,0.321745,0.411849,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,2.0,0.0,2.0,0.0,-697.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
49,100056,0,Cash loans,M,Y,Y,0,360000.0,1506816.0,49927.5,1350000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010006,-18264,-9523,-5504.0,-1797,1,1,0,1,0,0,Laborers,2.0,2,2,THURSDAY,10,0,0,0,0,1,1,Transport: type 2,0.523934,0.535276,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,1.0,1.0,1.0,1.0,-1498.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.026392,-18632,-6977,-3904.0,-1937,1,1,0,1,1,0,Managers,3.0,2,2,TUESDAY,10,0,0,0,0,0,0,Services,0.713355,0.309275,0.9811,0.4583,0.9811,0.4583,0.9811,0.4583,0.5149,No,2.0,0.0,2.0,0.0,-1285.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307460,456199,0,Cash loans,M,Y,N,1,382500.0,745429.5,24354.0,643500.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.007020,-14391,-175,-4213.0,-4468,1,1,1,1,1,0,Security staff,3.0,2,2,TUESDAY,12,0,0,0,0,1,1,Government,0.575246,0.479449,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,0.0,0.0,0.0,0.0,-1994.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
307477,456217,0,Cash loans,F,N,Y,0,360000.0,796396.5,38443.5,643500.0,Unaccompanied,State servant,Higher education,Civil marriage,House / apartment,0.007020,-18463,-698,-3168.0,-2021,1,1,0,1,0,0,Medicine staff,2.0,2,2,WEDNESDAY,13,0,0,0,0,0,0,Medicine,0.547811,0.667458,0.9876,0.1667,0.9876,0.1667,0.9876,0.1667,0.0581,No,0.0,0.0,0.0,0.0,-1353.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307484,456228,0,Cash loans,F,Y,N,0,540000.0,545040.0,35617.5,450000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,Rented apartment,0.032561,-12847,-328,-2531.0,-35,1,1,0,1,1,1,Managers,2.0,1,1,MONDAY,13,0,0,0,0,0,0,Business Entity Type 3,0.739703,0.535276,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,0.0,0.0,0.0,0.0,-1578.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.0,1575000.0,43443.0,1575000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-20965,-1618,-1764.0,-4410,1,1,0,1,0,0,Sales staff,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Self-employed,0.599173,0.365617,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307496,456240,0,Revolving loans,F,N,N,0,360000.0,337500.0,16875.0,337500.0,Family,Working,Higher education,Married,House / apartment,0.004960,-17345,-2178,-4262.0,-876,1,1,0,1,0,0,Cooking staff,2.0,2,2,THURSDAY,13,0,0,0,0,0,0,Self-employed,0.512081,0.486653,0.9816,0.1667,0.9816,0.1667,0.9816,0.1667,0.0688,No,0.0,0.0,0.0,0.0,-826.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

In [24]:
def find_outliers(df):
    outlier_dict = {}
    for col in df.select_dtypes(include=['int64', 'float64']).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = df[(df[col] < lower) | (df[col] > upper)]
        outlier_dict[col] = len(outliers)
    return outlier_dict

find_outliers(df_app_train)

{'SK_ID_CURR': 0,
 'CNT_CHILDREN': 4272,
 'AMT_INCOME_TOTAL': 14035,
 'AMT_CREDIT': 6562,
 'AMT_ANNUITY': 7504,
 'AMT_GOODS_PRICE': 14728,
 'REGION_POPULATION_RELATIVE': 8412,
 'DAYS_BIRTH': 0,
 'DAYS_EMPLOYED': 72217,
 'DAYS_REGISTRATION': 659,
 'DAYS_ID_PUBLISH': 0,
 'FLAG_MOBIL': 1,
 'CNT_FAM_MEMBERS': 4007,
 'HOUR_APPR_PROCESS_START': 2257,
 'REG_REGION_NOT_WORK_REGION': 15612,
 'EXT_SOURCE_2': 0,
 'EXT_SOURCE_3': 4313,
 'YEARS_BEGINEXPLUATATION_AVG': 142016,
 'FLOORSMAX_AVG': 92616,
 'YEARS_BEGINEXPLUATATION_MODE': 141861,
 'FLOORSMAX_MODE': 88941,
 'YEARS_BEGINEXPLUATATION_MEDI': 142141,
 'FLOORSMAX_MEDI': 90884,
 'TOTALAREA_MODE': 141917,
 'OBS_30_CNT_SOCIAL_CIRCLE': 19971,
 'DEF_30_CNT_SOCIAL_CIRCLE': 35166,
 'OBS_60_CNT_SOCIAL_CIRCLE': 19564,
 'DEF_60_CNT_SOCIAL_CIRCLE': 25769,
 'DAYS_LAST_PHONE_CHANGE': 435,
 'FLAG_DOCUMENT_2': 13,
 'FLAG_DOCUMENT_3': 0,
 'FLAG_DOCUMENT_4': 25,
 'FLAG_DOCUMENT_5': 4648,
 'FLAG_DOCUMENT_6': 27078,
 'FLAG_DOCUMENT_7': 59,
 'FLAG_DOCUMENT_8': 25024,
 'FLAG_DOCUMENT_9': 1198,
 'FLAG_DOCUMENT_10': 7,
 'FLAG_DOCUMENT_11': 1203,
 'FLAG_DOCUMENT_12': 2,
 'FLAG_DOCUMENT_13': 1084,
 'FLAG_DOCUMENT_14': 903,
 'FLAG_DOCUMENT_15': 372,
 'FLAG_DOCUMENT_16': 3053,
 'FLAG_DOCUMENT_17': 82,
 'FLAG_DOCUMENT_18': 2500,
 'FLAG_DOCUMENT_19': 183,
 'FLAG_DOCUMENT_20': 156,
 'FLAG_DOCUMENT_21': 103,
 'AMT_REQ_CREDIT_BUREAU_QRT': 50575}

####winsorisasi

In [25]:
import numpy as np

def winsorize_series(s):
    Q1 = s.quantile(0.25)
    Q3 = s.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return np.clip(s, lower, upper)

cols = ['AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'AMT_ANNUITY']

for c in cols:
    df_app_train[c] = winsorize_series(df_app_train[c])

###Featuring Engineering

In [26]:
df_app_train['CREDIT_TO_INCOME'] = df_app_train['AMT_CREDIT'] / df_app_train['AMT_INCOME_TOTAL']
df_app_train['ANNUITY_TO_INCOME'] = df_app_train['AMT_ANNUITY'] / df_app_train['AMT_INCOME_TOTAL']
df_app_train['GOODS_TO_CREDIT'] = df_app_train['AMT_GOODS_PRICE'] / df_app_train['AMT_CREDIT']

df_app_train['INCOME_PER_PERSON'] = df_app_train['AMT_INCOME_TOTAL'] / df_app_train['CNT_FAM_MEMBERS']
df_app_train['CREDIT_TERM'] = df_app_train['AMT_CREDIT'] / df_app_train['AMT_ANNUITY']
df_app_train['PAYMENT_RATE'] = df_app_train['AMT_ANNUITY'] / df_app_train['AMT_CREDIT']

# hubungan umur & pengajuan
df_app_train['AGE_YEARS'] = (-df_app_train['DAYS_BIRTH']) / 365
df_app_train['EMPLOYED_YEARS'] = (-df_app_train['DAYS_EMPLOYED']) / 365

# ratio tambahan
df_app_train['INCOME_CREDIT_PERC'] = df_app_train['AMT_INCOME_TOTAL'] / df_app_train['AMT_CREDIT']
df_app_train['ANNUITY_CREDIT_PERC'] = df_app_train['AMT_ANNUITY'] / df_app_train['AMT_CREDIT']

In [27]:
#ambil data train tanpa count featuring engineering untuk eda
df_app_train.to_csv('for_eda.csv', index=False)

In [ ]:
df_app_train.select_dtypes('category').nunique()

TARGET                          2
NAME_CONTRACT_TYPE              2
CODE_GENDER                     3
FLAG_OWN_CAR                    2
FLAG_OWN_REALTY                 2
NAME_TYPE_SUITE                 7
NAME_INCOME_TYPE                8
NAME_EDUCATION_TYPE             5
NAME_FAMILY_STATUS              6
NAME_HOUSING_TYPE               6
FLAG_EMP_PHONE                  2
FLAG_WORK_PHONE                 2
FLAG_CONT_MOBILE                2
FLAG_PHONE                      2
FLAG_EMAIL                      2
OCCUPATION_TYPE                18
REGION_RATING_CLIENT            3
REGION_RATING_CLIENT_W_CITY     3
WEEKDAY_APPR_PROCESS_START      7
REG_REGION_NOT_LIVE_REGION      2
LIVE_REGION_NOT_WORK_REGION     2
REG_CITY_NOT_LIVE_CITY          2
REG_CITY_NOT_WORK_CITY          2
LIVE_CITY_NOT_WORK_CITY         2
ORGANIZATION_TYPE              58
EMERGENCYSTATE_MODE             2
AMT_REQ_CREDIT_BUREAU_HOUR      5
AMT_REQ_CREDIT_BUREAU_DAY       9
AMT_REQ_CREDIT_BUREAU_WEEK      9
AMT_REQ_CREDIT_BUREAU_MON      24
AMT_REQ_CREDIT_BUREAU_YEAR     25
dtype: int64

In [ ]:
cat_app_train = [
    "NAME_CONTRACT_TYPE",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "NAME_TYPE_SUITE",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "FLAG_EMP_PHONE",
    "FLAG_WORK_PHONE",
    "FLAG_CONT_MOBILE",
    "FLAG_PHONE",
    "FLAG_EMAIL",
    "OCCUPATION_TYPE",
    "REGION_RATING_CLIENT",
    "REGION_RATING_CLIENT_W_CITY",
    "WEEKDAY_APPR_PROCESS_START",
    "REG_REGION_NOT_LIVE_REGION",
    "LIVE_REGION_NOT_WORK_REGION",
    "REG_CITY_NOT_LIVE_CITY",
    "REG_CITY_NOT_WORK_CITY",
    "LIVE_CITY_NOT_WORK_CITY",
    "ORGANIZATION_TYPE",
    "EMERGENCYSTATE_MODE",
    "AMT_REQ_CREDIT_BUREAU_HOUR",
    "AMT_REQ_CREDIT_BUREAU_DAY",
    "AMT_REQ_CREDIT_BUREAU_WEEK",
    "AMT_REQ_CREDIT_BUREAU_MON",
    "AMT_REQ_CREDIT_BUREAU_YEAR"
]
enc_app_train = df_app_train
for col in cat_app_train:
    enc_app_train[col + '_count'] = enc_app_train[col].map(enc_app_train[col].value_counts())

In [ ]:
enc_app_train = enc_app_train.drop(columns=cat_app_train)

##application_test.csv

###Data Type

In [ ]:
df_app_test.dtypes

SK_ID_CURR                      int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
FLAG_OWN_REALTY                object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 121, dtype: object

In [ ]:
# Daftar kolom yang ingin diubah ke tipe category
cols_to_category = [
    'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
    'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
    'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
    'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE',
    'FLAG_CONT_MOBILE', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE',
    'FLAG_PHONE', 'FLAG_EMAIL', 'REGION_RATING_CLIENT',
    'REGION_RATING_CLIENT_W_CITY', 'REG_REGION_NOT_LIVE_REGION',
    'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY',
    'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY',
    'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
    'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
    'AMT_REQ_CREDIT_BUREAU_YEAR'
]

# Ubah semuanya jadi kategori untuk df_app_test
for col in cols_to_category:
    if col in df_app_test.columns:  # biar aman kalau ada kolom yang tidak ada di test
        df_app_test[col] = df_app_test[col].astype('category')

# Cek hasilnya
df_app_test[cols_to_category].dtypes

NAME_CONTRACT_TYPE             category
CODE_GENDER                    category
FLAG_OWN_CAR                   category
FLAG_OWN_REALTY                category
NAME_TYPE_SUITE                category
NAME_INCOME_TYPE               category
NAME_EDUCATION_TYPE            category
NAME_FAMILY_STATUS             category
NAME_HOUSING_TYPE              category
OCCUPATION_TYPE                category
WEEKDAY_APPR_PROCESS_START     category
ORGANIZATION_TYPE              category
FONDKAPREMONT_MODE             category
HOUSETYPE_MODE                 category
WALLSMATERIAL_MODE             category
EMERGENCYSTATE_MODE            category
FLAG_CONT_MOBILE               category
FLAG_EMP_PHONE                 category
FLAG_WORK_PHONE                category
FLAG_PHONE                     category
FLAG_EMAIL                     category
REGION_RATING_CLIENT           category
REGION_RATING_CLIENT_W_CITY    category
REG_REGION_NOT_LIVE_REGION     category
LIVE_REGION_NOT_WORK_REGION    category
REG_CITY_NOT_LIVE_CITY         category
REG_CITY_NOT_WORK_CITY         category
LIVE_CITY_NOT_WORK_CITY        category
AMT_REQ_CREDIT_BUREAU_HOUR     category
AMT_REQ_CREDIT_BUREAU_DAY      category
AMT_REQ_CREDIT_BUREAU_WEEK     category
AMT_REQ_CREDIT_BUREAU_MON      category
AMT_REQ_CREDIT_BUREAU_YEAR     category
dtype: object

### Missing Value

In [ ]:
df_app_test.isnull().sum().sort_values(ascending=False)

COMMONAREA_AVG              33495
COMMONAREA_MEDI             33495
COMMONAREA_MODE             33495
NONLIVINGAPARTMENTS_AVG     33347
NONLIVINGAPARTMENTS_MEDI    33347
                            ...
FLAG_DOCUMENT_16                0
FLAG_DOCUMENT_15                0
FLAG_DOCUMENT_14                0
FLAG_DOCUMENT_20                0
FLAG_DOCUMENT_21                0
Length: 121, dtype: int64

In [ ]:
num_cols_test = df_app_test.select_dtypes(include=['float']).columns
df_app_test[num_cols_test] = df_app_test[num_cols_test].fillna(df_app_test[num_cols_test].median())

In [ ]:
for col in df_app_test.select_dtypes('category').columns:
    df_app_test[col].fillna(df_app_test[col].mode()[0], inplace=True)

/tmp/ipython-input-1326256827.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_app_test[col].fillna(df_app_test[col].mode()[0], inplace=True)

###Outlier

In [ ]:
df_app_test.describe()

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,REG_REGION_NOT_WORK_REGION,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_QRT
count,48744.000000,48744.000000,4.874400e+04,4.874400e+04,48744.000000,4.874400e+04,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.0,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.0,48744.000000,48744.0,48744.0,48744.0,48744.0,48744.0,48744.0,48744.000000,48744.0,48744.0,48744.0,48744.000000
mean,277796.676350,0.397054,1.784318e+05,5.167404e+05,29424.651219,4.626188e+05,0.021226,-16068.084605,67485.366322,-4967.652716,-3051.712949,9.939193,0.999979,2.146767,12.007365,0.055166,0.503535,0.518028,0.503483,0.107888,0.083280,0.980128,0.753789,0.030497,0.041157,0.145064,0.201648,0.218360,0.056241,0.085519,0.095237,0.002916,0.015695,0.102427,0.082194,0.979843,0.758309,0.028097,0.038935,0.142681,0.199397,0.216834,0.054487,0.091255,0.093492,0.002640,0.013734,0.108005,0.082878,0.980125,0.757057,0.030159,0.040654,0.144766,0.201360,0.218167,0.056900,0.086846,0.096086,0.002836,0.015278,0.090221,1.446783,0.143566,1.434884,0.101079,-1077.766228,0.0,0.786620,0.000103,0.014751,0.087477,0.000041,0.088462,0.004493,0.0,0.001169,0.0,0.0,0.0,0.0,0.0,0.0,0.001559,0.0,0.0,0.0,0.479033
std,103169.547296,0.709047,1.015226e+05,3.653970e+05,16012.584824,3.367102e+05,0.014428,4325.900393,144348.507136,3552.612035,1569.276709,6.784398,0.004529,0.890423,3.278172,0.228306,0.156090,0.181264,0.171978,0.082117,0.053975,0.035968,0.066726,0.047768,0.105688,0.072663,0.111562,0.096388,0.053918,0.058013,0.084434,0.027732,0.050727,0.082786,0.054708,0.039229,0.064888,0.046846,0.103723,0.073253,0.110327,0.096127,0.054608,0.061060,0.085759,0.026508,0.051889,0.082926,0.053626,0.036219,0.066026,0.047803,0.105384,0.072824,0.111664,0.096499,0.054563,0.058794,0.085640,0.027380,0.051457,0.083560,3.607153,0.514272,3.579231,0.403679,878.920740,0.0,0.409698,0.010128,0.120554,0.282536,0.006405,0.283969,0.066879,0.0,0.034176,0.0,0.0,0.0,0.0,0.0,0.0,0.039456,0.0,0.0,0.0,0.673449
min,100001.000000,0.000000,2.694150e+04,4.500000e+04,2295.000000,4.500000e+04,0.000253,-25195.000000,-17463.000000,-23722.000000,-6348.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.013458,0.000008,0.000527,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4361.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
25%,188557.750000,0.000000,1.125000e+05,2.606400e+05,17973.000000,2.250000e+05,0.010006,-19637.000000,-2910.000000,-7459.250000,-4448.000000,9.000000,1.000000,2.000000,10.000000,0.000000,0.465287,0.408082,0.399676,0.090700,0.078100,0.981100,0.755200,0.022700,0.000000,0.137900,0.166700,0.208300,0.048300,0.075600,0.074900,0.000000,0.003800,0.084000,0.077000,0.980600,0.758300,0.020300,0.000000,0.137900,0.166700,0.208300,0.046200,0.081700,0.073300,0.000000,0.001200,0.089500,0.077800,0.981100,0.758500,0.022300,0.000000,0.137900,0.166700,0.208300,0.048800,0.077000,0.075400,0.000000,0.003100,0.067300,0.000000,0.000000,0.000000,0.000000,-1766.250000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
50%,277549.000000,0.000000,1.575000e+05,4.500000e+05,26199.000000,3.960000e+05,0.018850,-15785.000000,-1293.000000,-4490.000000,-3234.000000,9.000000,1.000000,2.000000,12.000000,0.000000,0.506771,0.558758,0.519097,0.092800,0.078100,0.981600,0.755200,0.022700,0.000000,0.137900,0.166700,0.208300,0.048300,0.075600,0.077000,0.000000,0.003800,0.085100,0.077000,0.981600,0.758300,0.020300,0.000000,0.137900,0.166700,0.208300,0.046200,0.081700,0.075100,0.000000,0.001200,0.092600,0.077800,0.981600,0.758500,0.022300,0.000000,0.137900,0.166700,0.208300,0.048800,0.077000,0.077600,0.000000,0.003100,0.070700,0.000000,0.000000,0.000000,0.000000,-863.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
75%,367555.500000,1.000000,2.250000e+05,6.750000e+05,37390.500000,6.300000e+05,0.028663,-12496.000000,-296.000000,-1901.000000,-1706.000000,9.000000,1.000000,3.000000,14.000000,0.000000,0.551291,0.658480,0.624615,0.092800,0.078100,0.982100,0.755200,0.022700,0.000000,0.137900,0.166700,0.208300,0.048300,0.075600,0.079200,0.000000,0.003800,0.088200,0.077000,0.982100,0.758300,0.020300,0.000000,0.137900,0.166700,0.208300,0.046200,0.081700,0.078000,0.000000,0.001200,0.093700,0.077800,0.982100,0.758500,0.022300,0.000000,0.137900,0.166700,0.208300,0.048800,0.077000,0.079600,0.000000,0.003100,0.075000,2.000000,0.000000,2.000000,0.000000,-363.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.000000
max,456250.000000,20.000000,4.410000e+06,2.245500e+06,180576.000000,2.245500e+06,0.072508,-7338.000000,365243.000000,0.000000,0.000000,74.000000,1.000000,21.000000,23.000000,1.000000,0.939145,0.855000,0.882530,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,354.000000,34.000000,351.000000,24.000000,0.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,7.000000

In [ ]:
detect_outliers_iqr(df_app_test, 'AMT_INCOME_TOTAL')

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
38,100280,Cash loans,M,Y,Y,2,405000.0,513040.5,61015.5,472500.0,Unaccompanied,Commercial associate,Incomplete higher,Married,House / apartment,0.046220,-14342,-976,-2238.0,-1168,3.0,1,1,0,1,0,1,Managers,4.0,1,1,TUESDAY,10,0,1,1,0,0,0,Business Entity Type 3,0.857564,0.745886,0.681706,0.0928,0.0781,0.9816,0.7552,0.0227,0.00,0.1379,0.1667,0.2083,0.0483,0.0756,0.0770,0.0000,0.0038,0.0851,0.0770,0.9816,0.7583,0.0203,0.0000,0.1379,0.1667,0.2083,0.0462,0.0817,0.0751,0.0000,0.0012,0.0926,0.0778,0.9816,0.7585,0.0223,0.00,0.1379,0.1667,0.2083,0.0488,0.0770,0.0776,0.0000,0.0031,reg oper account,block of flats,0.0707,Panel,No,0.0,0.0,0.0,0.0,-329.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
93,100747,Cash loans,M,Y,Y,0,495000.0,691551.0,54769.5,625500.0,"Spouse, partner",Commercial associate,Incomplete higher,Civil marriage,House / apartment,0.007305,-8842,-839,-4283.0,-1485,3.0,1,1,1,1,1,0,Drivers,2.0,3,3,THURSDAY,9,0,0,0,0,0,0,Business Entity Type 3,0.506771,0.562719,0.307737,0.1485,0.0912,0.9866,0.8164,0.0219,0.16,0.1379,0.3333,0.0417,0.0000,0.1210,0.1583,0.0000,0.0000,0.1513,0.0946,0.9866,0.8236,0.0221,0.1611,0.1379,0.3333,0.0417,0.0000,0.1322,0.1649,0.0000,0.0000,0.1499,0.0912,0.9866,0.8189,0.0221,0.16,0.1379,0.3333,0.0417,0.0000,0.1231,0.1611,0.0000,0.0000,reg oper account,block of flats,0.1245,"Stone, brick",No,0.0,0.0,0.0,0.0,-356.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,4.0,0.0
188,101308,Cash loans,F,N,Y,1,540000.0,500490.0,59526.0,450000.0,Unaccompanied,Commercial associate,Higher education,Separated,House / apartment,0.032561,-12073,-360,-6119.0,-4374,9.0,1,1,0,1,1,0,Laborers,2.0,1,1,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.139795,0.704506,0.332851,0.1330,0.1151,0.9747,0.6532,0.0244,0.00,0.3103,0.1667,0.2083,0.0644,0.1072,0.1197,0.0058,0.0048,0.1334,0.1075,0.9747,0.6668,0.0230,0.0000,0.3103,0.1667,0.2083,0.0611,0.1166,0.1246,0.0000,0.0037,0.1343,0.1151,0.9747,0.6578,0.0245,0.00,0.3103,0.1667,0.2083,0.0655,0.1090,0.1218,0.0058,0.0049,reg oper account,block of flats,0.0949,Panel,No,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
206,101368,Cash loans,M,Y,Y,2,450000.0,675000.0,53460.0,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.072508,-14468,-3525,-4438.0,-3473,8.0,1,1,0,1,1,0,Managers,4.0,1,1,WEDNESDAY,9,0,0,0,0,0,0,Transport: type 4,0.676368,0.709431,0.622922,0.0619,0.0618,0.9737,0.6396,0.0000,0.00,0.1034,0.1667,0.2083,0.0000,0.0504,0.0506,0.0000,0.0000,0.0630,0.0641,0.9737,0.6537,0.0000,0.0000,0.1034,0.1667,0.2083,0.0000,0.0551,0.0527,0.0000,0.0000,0.0625,0.0618,0.9737,0.6444,0.0000,0.00,0.1034,0.1667,0.2083,0.0000,0.0513,0.0515,0.0000,0.0000,reg oper account,block of flats,0.0398,"Stone, brick",No,0.0,0.0,0.0,0.0,-1719.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
262,101762,Cash loans,F,N,N,0,675000.0,941580.0,98874.0,900000.0,Family,Working,Higher education,Married,House / apartment,0.072508,-17231,-2061,-7999.0,-774,9.0,1,1,0,1,1,0,Managers,2.0,1,1,SATURDAY,18,0,0,0,0,0,0,Other,0.753939,0.687135,0.452534,0.3804,0.0781,0.9811,0.7552,0.0227,0.64,0.2759,0.4583,0.2083,0.0483,0.0756,0.0770,0.0000,0.0038,0.3876,0.0770,0.9811,0.7583,0.0203,0.6445,0.2759,0.4583,0.2083,0.0462,0.0817,0.0751,0.0000,0.0012,0.3841,0.0778,0.9811,0.7585,0.0223,0.64,0.2759,0.4583,0.2083,0.0488,0.0770,0.0776,0.0000,0.0031,reg oper account,block of flats,0.3072,Panel,No,0.0,0.0,0.0,0.0,-1128.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48560,454707,Cash loans,F,N,N,2,441000.0,792162.0,40446.0,630000.0,Unaccompanied,State servant,Higher education,Separated,House / apartment,0.072508,-14604,-7241,-305.0,-2799,9.0,1,1,0,1,0,0,Managers,3.0,1,1,MONDAY,11,1,1,0,0,0,0,Security Ministries,0.718681,0.699686,0.710674,0.7144,0.2942,0.9861,0.8096,0.2973,1.00,0.4483,0.5417,0.5833,0.0000,0.5825,0.6426,0.0116,0.0100,0.7279,0.3053,0.9861,0.8171,0.3000,1.0000,0.4483,0.5417,0.5833,0.0000,0.6364,0.6695,0.0117,0.0106,0.7214,0.2942,0.9861,0.8121,0.2992,1.00,0.4483,0.5417,0.5833,0.0000,0.5926,0.6542,0.0116,0.0102,reg oper account,block of flats,0.5076,Panel,No,0.0,0.0,0.0,0.0,-2044.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48669,455583,Cash loans,F,N,Y,2,450000.0,553581.0,43866.0,472500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.010500,-14495,-1242,-6830.0,-5483,9.0,1,1,0,1,0,0,Managers,4.0,3,3,WEDNESDAY,13,0,0,0,0,0,0,Trade: type 7,0.770718,0.317408,0.670652,0.0495,0.0521,0.9881,0.8368,0.0096,0.00,0.1724,0.1250,0.1667,0.0142,0.0370,0.0298,0.0154,0.0065,0.0504,0.0541,0.9881,0.8432,0.0096,0.0000,0.1724,0.1250,0.1667,0.0145,0.0404,0.0311,0.0156,0.0069,0.0500,0.0521,0.9881,0.8390,0.0096,0.00,0.1724,0.1250,0.1667,0.0144,0.0376,0.0304,0.0155,0.0066,reg oper account,block of flats,0.0424,"Stone, brick",No,1.0,0.0,1.0,0.0,-291.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
48682,455703,Cash loans,F,Y,Y,1,450000.0,790830.0,57676.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.035792,-9952,-1437,-1376.0,-2263,7.0,1,1,0,1,0,1,Managers,3.0,2,2,FRIDAY,16,0,0,0,1,1,0,Business Entity Type 3,0.181947,0.558863,0.297087,0.0247,0.0000,0.9866,0.8164,0.0132,0.00,0.1034,0.0833,0.0417,0.0139,0.0202,0.0164,0.0000,0.0332,0.0252,0.0000,0.9866,0.8236,0.0133,0.0000,0.1034,0.0833,0.0417,0.0142,0.0220,0.0171,0.0000,0.0351,0.0250,0.0000,0.9866,0.8189,0.0133,0.00,0.1034,0.0833,0.0417,0.0141,0.0205,0.0167,0.0000,0.0339,reg oper spec account,terraced house,0.0201,"Stone, brick",No,1.0,0.0,1.0,0.0,-844.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48684,455748,Cash loans,M,Y,Y,1,441000.0,746280.0,59094.0,675000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.030755,-15731,-800,-9856.0,-1659,1.0,1,1,0,1,1,1,Managers,3.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,Business Entity Type 3,0.388840,0.682083,0.526295,0.0722,0.0760,0.9767,0.6804,0.0080,0.00,0.1379,0.1667,0.2083,0.0484,0.0756,0.0638,0.0000,0.0000,0.0735,0.0789,0.9767,0.6929,0.0081,0.0000,0.1379,0.1667,0.2083,0.0495,0.0817,0.0665,0.0000,0.0000,0.0729,0.0760,0.9767,0.6847,0.0081,0.00,0.1379,0.1667,0.2083,0.0493,0.0770,0.0650,0.0000,0.0000,reg oper account,block of flats,0.0502,"Stone, brick",No,8.0,0.0,8.0,0.0,-1423.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
48685,455749,Cash loans,M,N,N,0,432000.0,509400.0,40243.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.032561,-14780,-1483,-325.0,-2500,9.0,1,1,1,1,0,0,Low-skill Laborers,2.0,1,1,WEDNESDAY,14,0,0,0,0,0,0,Business Entity Type 3,0.506771,0.529952,0.528093,0.1031,0.0789,0.9757,0.7552,0.0227,0.00,0.1724,0.1667,0.2083,0.1092,0.0756,0.0896,0.0000,0.0066,0.1050,0.0819,0.9757,0.7583,0.0203,0.0000,0.1724,0.1667,0.2083,0.1116,0.0817,0.0934,0.0000,0.0070,0.1041,0.0789,0.9757,0.7585,0.0223,0.00,0.1724,0.1667,0.2083,0.1111,0.0770,0.0912,0.0000,0.0068,reg oper account,block of flats,0.0719,Panel,No,0.0,0.0,0.0,0.0,-1288.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
find_outliers(df_app_test)

{'SK_ID_CURR': 0,
 'CNT_CHILDREN': 606,
 'AMT_INCOME_TOTAL': 1597,
 'AMT_CREDIT': 2350,
 'AMT_ANNUITY': 1173,
 'AMT_GOODS_PRICE': 2122,
 'REGION_POPULATION_RELATIVE': 1565,
 'DAYS_BIRTH': 0,
 'DAYS_EMPLOYED': 11630,
 'DAYS_REGISTRATION': 109,
 'DAYS_ID_PUBLISH': 0,
 'OWN_CAR_AGE': 15583,
 'FLAG_MOBIL': 1,
 'CNT_FAM_MEMBERS': 576,
 'HOUR_APPR_PROCESS_START': 407,
 'REG_REGION_NOT_WORK_REGION': 2689,
 'EXT_SOURCE_1': 13218,
 'EXT_SOURCE_2': 412,
 'EXT_SOURCE_3': 218,
 'APARTMENTS_AVG': 23390,
 'BASEMENTAREA_AVG': 21078,
 'YEARS_BEGINEXPLUATATION_AVG': 20120,
 'YEARS_BUILD_AVG': 16533,
 'COMMONAREA_AVG': 15230,
 'ELEVATORS_AVG': 10088,
 'ENTRANCES_AVG': 19482,
 'FLOORSMAX_AVG': 15305,
 'FLOORSMIN_AVG': 10941,
 'LANDAREA_AVG': 20472,
 'LIVINGAPARTMENTS_AVG': 15492,
 'LIVINGAREA_AVG': 22102,
 'NONLIVINGAPARTMENTS_AVG': 6582,
 'NONLIVINGAREA_AVG': 22603,
 'APARTMENTS_MODE': 21287,
 'BASEMENTAREA_MODE': 21090,
 'YEARS_BEGINEXPLUATATION_MODE': 18266,
 'YEARS_BUILD_MODE': 16532,
 'COMMONAREA_MODE': 15225,
 'ELEVATORS_MODE': 9385,
 'ENTRANCES_MODE': 19138,
 'FLOORSMAX_MODE': 14649,
 'FLOORSMIN_MODE': 10673,
 'LANDAREA_MODE': 20483,
 'LIVINGAPARTMENTS_MODE': 15854,
 'LIVINGAREA_MODE': 21637,
 'NONLIVINGAPARTMENTS_MODE': 5759,
 'NONLIVINGAREA_MODE': 22590,
 'APARTMENTS_MEDI': 21558,
 'BASEMENTAREA_MEDI': 21075,
 'YEARS_BEGINEXPLUATATION_MEDI': 20168,
 'YEARS_BUILD_MEDI': 16531,
 'COMMONAREA_MEDI': 15235,
 'ELEVATORS_MEDI': 9817,
 'ENTRANCES_MEDI': 19206,
 'FLOORSMAX_MEDI': 14980,
 'FLOORSMIN_MEDI': 10778,
 'LANDAREA_MEDI': 20468,
 'LIVINGAPARTMENTS_MEDI': 15460,
 'LIVINGAREA_MEDI': 22140,
 'NONLIVINGAPARTMENTS_MEDI': 6280,
 'NONLIVINGAREA_MEDI': 22588,
 'TOTALAREA_MODE': 20113,
 'OBS_30_CNT_SOCIAL_CIRCLE': 3236,
 'DEF_30_CNT_SOCIAL_CIRCLE': 5520,
 'OBS_60_CNT_SOCIAL_CIRCLE': 3197,
 'DEF_60_CNT_SOCIAL_CIRCLE': 4101,
 'DAYS_LAST_PHONE_CHANGE': 29,
 'FLAG_DOCUMENT_2': 0,
 'FLAG_DOCUMENT_3': 10401,
 'FLAG_DOCUMENT_4': 5,
 'FLAG_DOCUMENT_5': 719,
 'FLAG_DOCUMENT_6': 4264,
 'FLAG_DOCUMENT_7': 2,
 'FLAG_DOCUMENT_8': 4312,
 'FLAG_DOCUMENT_9': 219,
 'FLAG_DOCUMENT_10': 0,
 'FLAG_DOCUMENT_11': 57,
 'FLAG_DOCUMENT_12': 0,
 'FLAG_DOCUMENT_13': 0,
 'FLAG_DOCUMENT_14': 0,
 'FLAG_DOCUMENT_15': 0,
 'FLAG_DOCUMENT_16': 0,
 'FLAG_DOCUMENT_17': 0,
 'FLAG_DOCUMENT_18': 76,
 'FLAG_DOCUMENT_19': 0,
 'FLAG_DOCUMENT_20': 0,
 'FLAG_DOCUMENT_21': 0,
 'AMT_REQ_CREDIT_BUREAU_QRT': 565}

####winsorisasi

In [ ]:
import numpy as np

def winsorize_series(s):
    Q1 = s.quantile(0.25)
    Q3 = s.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return np.clip(s, lower, upper)

cols = ['AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'AMT_ANNUITY']

for c in cols:
    df_app_train[c] = winsorize_series(df_app_test[c])

####imputasi

In [ ]:
def impute_outlier_iqr(df, col_name):
    Q1 = df[col_name].quantile(0.25)
    Q3 = df[col_name].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # outlier → NaN
    df.loc[(df[col_name] < lower) | (df[col_name] > upper), col_name] = np.nan

    # imputasi median
    df[col_name] = df[col_name].fillna(df[col_name].mode()[0]) # mode() can return multiple values, take the first
    return df

cols_impute_outlier = [
    'OWN_CAR_AGE',
    'CNT_CHILDREN',
    'CNT_FAM_MEMBERS',
    'AMT_REQ_CREDIT_BUREAU_QRT',
]

for col in cols_impute_outlier:
    if col in df_app_test.columns:
        df_app_test = impute_outlier_iqr(df_app_test, col)

###Featuring Engineering

In [ ]:
df_app_test['CREDIT_TO_INCOME'] = df_app_test['AMT_CREDIT'] / df_app_test['AMT_INCOME_TOTAL']
df_app_test['ANNUITY_TO_INCOME'] = df_app_test['AMT_ANNUITY'] / df_app_test['AMT_INCOME_TOTAL']
df_app_test['GOODS_TO_CREDIT'] = df_app_test['AMT_GOODS_PRICE'] / df_app_test['AMT_CREDIT']

df_app_test['INCOME_PER_PERSON'] = df_app_test['AMT_INCOME_TOTAL'] / df_app_test['CNT_FAM_MEMBERS']
df_app_test['CREDIT_TERM'] = df_app_test['AMT_CREDIT'] / df_app_test['AMT_ANNUITY']
df_app_test['PAYMENT_RATE'] = df_app_test['AMT_ANNUITY'] / df_app_test['AMT_CREDIT']

# hubungan umur & pengajuan
df_app_test['AGE_YEARS'] = (-df_app_test['DAYS_BIRTH']) / 365
df_app_test['EMPLOYED_YEARS'] = (-df_app_test['DAYS_EMPLOYED']) / 365

# ratio tambahan
df_app_test['INCOME_CREDIT_PERC'] = df_app_test['AMT_INCOME_TOTAL'] / df_app_test['AMT_CREDIT']
df_app_test['ANNUITY_CREDIT_PERC'] = df_app_test['AMT_ANNUITY'] / df_app_test['AMT_CREDIT']

In [ ]:
import pandas as pd

class AutoCountEncoder:
    def __init__(self, drop_original=True, cat_dtypes=('object', 'category')):
        self.drop_original = drop_original
        self.cat_dtypes = cat_dtypes
        self.cols_ = []
        self.count_maps = {}   # <── DIDEFINISIKAN DI SINI SESUAI ERROR-MU

    def fit(self, df):
        # auto detect kolom kategori
        self.cols_ = df.select_dtypes(include=self.cat_dtypes).columns.tolist()

        # buat mapping frekuensi untuk tiap kolom kategori
        for col in self.cols_:
            # cast ke object biar tidak error categorical
            series_obj = df[col].astype('object')
            self.count_maps[col] = series_obj.value_counts()

        return self

    def transform(self, df):
        df_copy = df.copy()

        for col in self.cols_:
            df_copy[col] = df_copy[col].astype('object')
            df_copy[col + "_count"] = df_copy[col].map(self.count_maps[col]).fillna(0)

        if self.drop_original:
            df_copy = df_copy.drop(columns=self.cols_)

        return df_copy

    def fit_transform(self, df):
        self.fit(df)
        return self.transform(df)

In [ ]:
enc_app_test = AutoCountEncoder().fit_transform(df_app_test)

#previous_application.csv

##Data Type

In [ ]:
df_pre_app.dtypes

SK_ID_PREV                       int64
SK_ID_CURR                       int64
NAME_CONTRACT_TYPE              object
AMT_ANNUITY                    float64
AMT_APPLICATION                float64
AMT_CREDIT                     float64
AMT_DOWN_PAYMENT               float64
AMT_GOODS_PRICE                float64
WEEKDAY_APPR_PROCESS_START      object
HOUR_APPR_PROCESS_START          int64
FLAG_LAST_APPL_PER_CONTRACT     object
NFLAG_LAST_APPL_IN_DAY           int64
RATE_DOWN_PAYMENT              float64
RATE_INTEREST_PRIMARY          float64
RATE_INTEREST_PRIVILEGED       float64
NAME_CASH_LOAN_PURPOSE          object
NAME_CONTRACT_STATUS            object
DAYS_DECISION                    int64
NAME_PAYMENT_TYPE               object
CODE_REJECT_REASON              object
NAME_TYPE_SUITE                 object
NAME_CLIENT_TYPE                object
NAME_GOODS_CATEGORY             object
NAME_PORTFOLIO                  object
NAME_PRODUCT_TYPE               object
CHANNEL_TYPE                    object
SELLERPLACE_AREA                 int64
NAME_SELLER_INDUSTRY            object
CNT_PAYMENT                    float64
NAME_YIELD_GROUP                object
PRODUCT_COMBINATION             object
DAYS_FIRST_DRAWING             float64
DAYS_FIRST_DUE                 float64
DAYS_LAST_DUE_1ST_VERSION      float64
DAYS_LAST_DUE                  float64
DAYS_TERMINATION               float64
NFLAG_INSURED_ON_APPROVAL      float64
dtype: object

In [ ]:
df_pre_app.dtypes.astype(str).value_counts()

object     16
float64    15
int64       6
Name: count, dtype: int64

In [ ]:
object = df_pre_app.select_dtypes(include=['object']).columns
df_pre_app[object].nunique()

NAME_CONTRACT_TYPE              4
WEEKDAY_APPR_PROCESS_START      7
FLAG_LAST_APPL_PER_CONTRACT     2
NAME_CASH_LOAN_PURPOSE         25
NAME_CONTRACT_STATUS            4
NAME_PAYMENT_TYPE               4
CODE_REJECT_REASON              9
NAME_TYPE_SUITE                 7
NAME_CLIENT_TYPE                4
NAME_GOODS_CATEGORY            28
NAME_PORTFOLIO                  5
NAME_PRODUCT_TYPE               3
CHANNEL_TYPE                    8
NAME_SELLER_INDUSTRY           11
NAME_YIELD_GROUP                5
PRODUCT_COMBINATION            17
dtype: int64

In [ ]:
df_pre_app['NAME_CONTRACT_TYPE']=df_pre_app['NAME_CONTRACT_TYPE'].astype('category')
df_pre_app['WEEKDAY_APPR_PROCESS_START']=df_pre_app['WEEKDAY_APPR_PROCESS_START'].astype('category')
df_pre_app['NAME_CASH_LOAN_PURPOSE']=df_pre_app['NAME_CASH_LOAN_PURPOSE'].astype('category')
df_pre_app['CODE_REJECT_REASON']= df_pre_app['CODE_REJECT_REASON'].astype('category')
df_pre_app['NAME_TYPE_SUITE']=df_pre_app['NAME_TYPE_SUITE'].astype('category')
df_pre_app['NAME_CLIENT_TYPE']=df_pre_app['NAME_CLIENT_TYPE'].astype('category')
df_pre_app['NAME_GOODS_CATEGORY']=df_pre_app['NAME_GOODS_CATEGORY'].astype('category')
df_pre_app['NAME_PORTFOLIO']=df_pre_app['NAME_PORTFOLIO'].astype('category')
df_pre_app['NAME_PRODUCT_TYPE']=df_pre_app['NAME_PRODUCT_TYPE'].astype('category')
df_pre_app['CHANNEL_TYPE']=df_pre_app['CHANNEL_TYPE'].astype('category')
df_pre_app['NAME_YIELD_GROUP']=df_pre_app['NAME_YIELD_GROUP'].astype('category')
df_pre_app['PRODUCT_COMBINATION']=df_pre_app['PRODUCT_COMBINATION'].astype('category')
df_pre_app['NAME_CONTRACT_STATUS']=df_pre_app['NAME_CONTRACT_STATUS'].astype('category')
df_pre_app['NAME_PAYMENT_TYPE']=df_pre_app['NAME_PAYMENT_TYPE'].astype('category')
df_pre_app['NAME_SELLER_INDUSTRY']=df_pre_app['NAME_SELLER_INDUSTRY'].astype('category')
df_pre_app['FLAG_LAST_APPL_PER_CONTRACT']=df_pre_app['FLAG_LAST_APPL_PER_CONTRACT'].astype('category')

##Missing Value

In [ ]:
# Hitung persentase missing value per kolom
mv_percent = (df_pre_app.isnull().sum() / len(df_pre_app) * 100)

# Ambil tipe data tiap kolom
dtypes = df_pre_app.dtypes

# Gabungkan keduanya menjadi 1 tabel rapi
mv_table = pd.concat([mv_percent, dtypes], axis=1).sort_values(by=0, ascending=False)

# Tampilkan
mv_table

                                     0         1
RATE_INTEREST_PRIVILEGED     99.643698   float64
RATE_INTEREST_PRIMARY        99.643698   float64
AMT_DOWN_PAYMENT             53.636480   float64
RATE_DOWN_PAYMENT            53.636480   float64
NAME_TYPE_SUITE              49.119754  category
DAYS_TERMINATION             40.298129   float64
DAYS_FIRST_DRAWING           40.298129   float64
DAYS_FIRST_DUE               40.298129   float64
DAYS_LAST_DUE_1ST_VERSION    40.298129   float64
DAYS_LAST_DUE                40.298129   float64
NFLAG_INSURED_ON_APPROVAL    40.298129   float64
AMT_GOODS_PRICE              23.081773   float64
AMT_ANNUITY                  22.286665   float64
CNT_PAYMENT                  22.286366   float64
PRODUCT_COMBINATION           0.020716  category
AMT_CREDIT                    0.000060   float64
SK_ID_PREV                    0.000000     int64
AMT_APPLICATION               0.000000   float64
NAME_CONTRACT_TYPE            0.000000  category
SK_ID_CURR                    0.000000     int64
WEEKDAY_APPR_PROCESS_START    0.000000  category
CODE_REJECT_REASON            0.000000  category
NAME_PAYMENT_TYPE             0.000000  category
DAYS_DECISION                 0.000000     int64
NAME_CONTRACT_STATUS          0.000000  category
NAME_CASH_LOAN_PURPOSE        0.000000  category
HOUR_APPR_PROCESS_START       0.000000     int64
FLAG_LAST_APPL_PER_CONTRACT   0.000000  category
NFLAG_LAST_APPL_IN_DAY        0.000000     int64
NAME_SELLER_INDUSTRY          0.000000  category
SELLERPLACE_AREA              0.000000     int64
CHANNEL_TYPE                  0.000000  category
NAME_PRODUCT_TYPE             0.000000  category
NAME_GOODS_CATEGORY           0.000000  category
NAME_PORTFOLIO                0.000000  category
NAME_CLIENT_TYPE              0.000000  category
NAME_YIELD_GROUP              0.000000  category

In [ ]:
#menghapus mv yang lebih dari 60%
df_pre_app=df_pre_app.drop(columns=['RATE_INTEREST_PRIVILEGED', 'RATE_INTEREST_PRIMARY'])

In [ ]:
#mengisi mv kolom tipe float dengan median
num_cols = df_pre_app.select_dtypes(include=['float']).columns
df_pre_app[num_cols] = df_pre_app[num_cols].fillna(df_pre_app[num_cols].median())

In [ ]:
#mengisi mv kolom tipe category dengan modus
for col in df_pre_app.select_dtypes('category').columns:
    df_pre_app[col].fillna(df_pre_app[col].mode()[0], inplace=True)

/tmp/ipython-input-1140499716.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_pre_app[col].fillna(df_pre_app[col].mode()[0], inplace=True)

##Outlier

In [ ]:
df_pre_app.describe()

,SK_ID_PREV,SK_ID_CURR,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,HOUR_APPR_PROCESS_START,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,DAYS_DECISION,SELLERPLACE_AREA,CNT_PAYMENT,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
count,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06,1.670214e+06
mean,1.923089e+06,2.783572e+05,1.490651e+04,1.752339e+05,1.961140e+05,3.983717e+03,2.011815e+05,1.248418e+01,9.964675e-01,6.460158e-02,-8.806797e+02,3.139511e+02,1.515057e+01,3.514918e+05,7.919664e+03,2.001452e+04,4.550473e+04,4.874988e+04,1.985506e-01
std,5.325980e+05,1.028148e+05,1.317751e+04,2.927798e+05,3.185745e+05,1.446730e+04,2.808629e+05,3.334028e+00,5.932963e-02,7.473662e-02,7.790997e+02,7.127443e+03,1.295220e+01,6.962551e+04,5.643575e+04,8.424512e+04,1.216582e+05,1.251729e+05,3.989090e-01
min,1.000001e+06,1.000010e+05,0.000000e+00,0.000000e+00,0.000000e+00,-9.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,-1.497876e-05,-2.922000e+03,-1.000000e+00,0.000000e+00,-2.922000e+03,-2.892000e+03,-2.801000e+03,-2.889000e+03,-2.874000e+03,0.000000e+00
25%,1.461857e+06,1.893290e+05,7.547096e+03,1.872000e+04,2.416050e+04,1.638000e+03,6.750000e+04,1.000000e+01,1.000000e+00,5.160508e-02,-1.300000e+03,-1.000000e+00,1.000000e+01,3.652430e+05,-1.020000e+03,-5.800000e+02,-7.340000e+02,-6.950000e+02,0.000000e+00
50%,1.923110e+06,2.787145e+05,1.125000e+04,7.104600e+04,8.054100e+04,1.638000e+03,1.123200e+05,1.200000e+01,1.000000e+00,5.160508e-02,-5.810000e+02,3.000000e+00,1.200000e+01,3.652430e+05,-8.310000e+02,-3.610000e+02,-5.370000e+02,-4.990000e+02,0.000000e+00
75%,2.384280e+06,3.675140e+05,1.682403e+04,1.803600e+05,2.164185e+05,1.638000e+03,1.804050e+05,1.500000e+01,1.000000e+00,5.160508e-02,-2.800000e+02,8.200000e+01,1.600000e+01,3.652430e+05,-6.830000e+02,-1.870000e+02,-3.710000e+02,-3.340000e+02,0.000000e+00
max,2.845382e+06,4.562550e+05,4.180581e+05,6.905160e+06,6.905160e+06,3.060045e+06,6.905160e+06,2.300000e+01,1.000000e+00,1.000000e+00,-1.000000e+00,4.000000e+06,8.400000e+01,3.652430e+05,3.652430e+05,3.652430e+05,3.652430e+05,3.652430e+05,1.000000e+00

In [ ]:
df_pre_app[df_pre_app["RATE_DOWN_PAYMENT"] < 0]["RATE_DOWN_PAYMENT"].value_counts()

RATE_DOWN_PAYMENT
-0.000014    1
-0.000015    1
Name: count, dtype: int64

In [ ]:
cols = ["AMT_DOWN_PAYMENT", "RATE_DOWN_PAYMENT"]
df_pre_app = df_pre_app[(df_pre_app[cols] >= 0).all(axis=1)]

In [ ]:
find_outliers(df_pre_app)

{'SK_ID_PREV': 0,
 'SK_ID_CURR': 0,
 'AMT_ANNUITY': 162620,
 'AMT_APPLICATION': 208019,
 'AMT_CREDIT': 179989,
 'AMT_DOWN_PAYMENT': 774308,
 'AMT_GOODS_PRICE': 236035,
 'HOUR_APPR_PROCESS_START': 1639,
 'NFLAG_LAST_APPL_IN_DAY': 5900,
 'RATE_DOWN_PAYMENT': 774368,
 'DAYS_DECISION': 17571,
 'SELLERPLACE_AREA': 268087,
 'CNT_PAYMENT': 344916,
 'DAYS_FIRST_DRAWING': 62705,
 'DAYS_FIRST_DUE': 374760,
 'DAYS_LAST_DUE_1ST_VERSION': 431364,
 'DAYS_LAST_DUE': 468436,
 'DAYS_TERMINATION': 482992,
 'NFLAG_INSURED_ON_APPROVAL': 331622}

###winsorisasi

In [ ]:
col_out_pre = [
    'AMT_ANNUITY',
    'AMT_APPLICATION',
    'AMT_CREDIT',
    'AMT_DOWN_PAYMENT',
    'AMT_GOODS_PRICE',
    'HOUR_APPR_PROCESS_START',
    'NFLAG_LAST_APPL_IN_DAY',
    'RATE_DOWN_PAYMENT',
    'DAYS_DECISION',
    'SELLERPLACE_AREA',
    'CNT_PAYMENT',
    'DAYS_FIRST_DRAWING',
    'DAYS_FIRST_DUE',
    'DAYS_LAST_DUE_1ST_VERSION',
    'DAYS_LAST_DUE',
    'DAYS_TERMINATION',
    'NFLAG_INSURED_ON_APPROVAL'
]

for c in col_out_pre:
    df_pre_app[c] = winsorize_series(df_pre_app[c])

###imputasi

##Featuring Engineering

In [ ]:
cat_pre = df_pre_app.select_dtypes(include=['category']).columns
for col in cat_pre:
    df_pre_app[col + '_count'] = df_pre_app[col].map(df_pre_app[col].value_counts())

In [ ]:
import pandas as pd

class AutoCountEncoder:
    def __init__(self, drop_original=True, cat_dtypes=('object', 'category')):
        self.drop_original = drop_original
        self.cat_dtypes = cat_dtypes
        self.cols_ = []
        self.count_maps = {}   # <── DIDEFINISIKAN DI SINI SESUAI ERROR-MU

    def fit(self, df):
        # auto detect kolom kategori
        self.cols_ = df.select_dtypes(include=self.cat_dtypes).columns.tolist()

        # buat mapping frekuensi untuk tiap kolom kategori
        for col in self.cols_:
            # cast ke object biar tidak error categorical
            series_obj = df[col].astype('object')
            self.count_maps[col] = series_obj.value_counts()

        return self

    def transform(self, df):
        df_copy = df.copy()

        for col in self.cols_:
            df_copy[col] = df_copy[col].astype('object')
            df_copy[col + "_count"] = df_copy[col].map(self.count_maps[col]).fillna(0)

        if self.drop_original:
            df_copy = df_copy.drop(columns=self.cols_)

        return df_copy

    def fit_transform(self, df):
        self.fit(df)
        return self.transform(df)

In [ ]:
encoder = AutoCountEncoder()
enc_pre_app = encoder.fit_transform(df_pre_app)

hasil semua cleaning disimpan dengan nama enc_pre_app

#credit_card_balance.csv

##Data Type

In [ ]:
df_credit.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,1800.0,1800.0,0.000,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,2250.0,2250.0,60175.080,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,2250.0,2250.0,26926.425,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,11925.0,11925.0,224949.285,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [ ]:
df_credit.dtypes.astype(str).value_counts()

float64    15
int64       7
object      1
Name: count, dtype: int64

In [ ]:
df_credit['NAME_CONTRACT_STATUS'].unique()

array(['Active', 'Completed', 'Demand', 'Signed', 'Sent proposal',
       'Refused', 'Approved'], dtype=object)

In [ ]:
obj_df_credit = df_credit.select_dtypes(include=['object']).columns
for col in obj_df_credit:
    df_credit[col] = df_credit[col].astype('category')

##Missing Value

In [ ]:
(df_credit.isnull().sum()/len(df_credit)*100).sort_values(ascending=False)

AMT_PAYMENT_CURRENT           19.998063
CNT_DRAWINGS_POS_CURRENT      19.524872
AMT_DRAWINGS_ATM_CURRENT      19.524872
CNT_DRAWINGS_ATM_CURRENT      19.524872
AMT_DRAWINGS_POS_CURRENT      19.524872
AMT_DRAWINGS_OTHER_CURRENT    19.524872
CNT_DRAWINGS_OTHER_CURRENT    19.524872
CNT_INSTALMENT_MATURE_CUM      7.948208
AMT_INST_MIN_REGULARITY        7.948208
AMT_DRAWINGS_CURRENT           0.000000
AMT_CREDIT_LIMIT_ACTUAL        0.000000
SK_ID_PREV                     0.000000
SK_ID_CURR                     0.000000
AMT_BALANCE                    0.000000
MONTHS_BALANCE                 0.000000
AMT_TOTAL_RECEIVABLE           0.000000
AMT_RECIVABLE                  0.000000
AMT_RECEIVABLE_PRINCIPAL       0.000000
AMT_PAYMENT_TOTAL_CURRENT      0.000000
CNT_DRAWINGS_CURRENT           0.000000
NAME_CONTRACT_STATUS           0.000000
SK_DPD                         0.000000
SK_DPD_DEF                     0.000000
dtype: float64

In [ ]:
#mengisi mv kolom tipe float dengan median
num_cols = df_credit.select_dtypes(include=['float','integer']).columns
df_credit[num_cols] = df_credit[num_cols].fillna(df_credit[num_cols].median())

##Outlier

In [ ]:
df_credit.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
count,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06
mean,1.904504e+06,2.783242e+05,-3.452192e+01,5.830016e+04,1.538080e+05,4.797384e+03,7.433388e+03,2.319048e+02,2.389150e+03,3.258821e+03,8.765117e+03,7.588857e+03,5.596588e+04,5.808881e+04,5.809829e+04,2.490295e-01,7.031439e-01,3.872862e-03,4.502415e-01,2.036209e+01,9.283667e+00,3.316220e-01
std,5.364695e+05,1.027045e+05,2.666775e+01,1.063070e+05,1.651457e+05,2.543070e+04,3.384608e+04,7.358721e+03,1.869353e+04,5.457656e+03,3.241165e+04,3.200599e+04,1.025336e+05,1.059654e+05,1.059718e+05,9.947390e-01,3.190347e+00,7.415793e-02,2.915566e+00,1.930254e+01,9.751570e+01,2.147923e+01
min,1.000018e+06,1.000060e+05,-9.600000e+01,-4.202502e+05,0.000000e+00,-6.827310e+03,-6.211620e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-4.233058e+05,-4.202502e+05,-4.202502e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.434385e+06,1.895170e+05,-5.500000e+01,0.000000e+00,4.500000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.479500e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00
50%,1.897122e+06,2.783960e+05,-2.800000e+01,0.000000e+00,1.125000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.702700e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,0.000000e+00,0.000000e+00
75%,2.369328e+06,3.675800e+05,-1.100000e+01,8.904669e+04,1.800000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.625000e+03,7.875000e+03,6.750000e+03,8.535924e+04,8.889949e+04,8.891451e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.100000e+01,0.000000e+00,0.000000e+00
max,2.843496e+06,4.562500e+05,-1.000000e+00,1.505902e+06,1.350000e+06,2.115000e+06,2.287098e+06,1.529847e+06,2.239274e+06,2.028820e+05,4.289207e+06,4.278316e+06,1.472317e+06,1.493338e+06,1.493338e+06,5.100000e+01,1.650000e+02,1.200000e+01,1.650000e+02,1.200000e+02,3.260000e+03,3.260000e+03

In [ ]:
df_credit['AMT_TOTAL_RECEIVABLE']=df_credit['AMT_TOTAL_RECEIVABLE'].mask(df_credit['AMT_TOTAL_RECEIVABLE'] < 0).fillna(df_credit['AMT_TOTAL_RECEIVABLE'].median())

In [ ]:
noise_credit = ['AMT_BALANCE', 'AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_TOTAL_RECEIVABLE']

df_credit[noise_credit] = df_credit[noise_credit].mask(df_credit[noise_credit] < 0)

In [ ]:
find_outliers(df_credit)

{'SK_ID_PREV': 0,
 'SK_ID_CURR': 0,
 'MONTHS_BALANCE': 0,
 'AMT_BALANCE': 247788,
 'AMT_CREDIT_LIMIT_ACTUAL': 404927,
 'AMT_DRAWINGS_ATM_CURRENT': 424777,
 'AMT_DRAWINGS_CURRENT': 616866,
 'AMT_DRAWINGS_OTHER_CURRENT': 12333,
 'AMT_DRAWINGS_POS_CURRENT': 264901,
 'AMT_INST_MIN_REGULARITY': 155560,
 'AMT_PAYMENT_CURRENT': 304208,
 'AMT_PAYMENT_TOTAL_CURRENT': 324742,
 'AMT_RECEIVABLE_PRINCIPAL': 250242,
 'AMT_RECIVABLE': 247510,
 'AMT_TOTAL_RECEIVABLE': 247464,
 'CNT_DRAWINGS_ATM_CURRENT': 424778,
 'CNT_DRAWINGS_CURRENT': 610360,
 'CNT_DRAWINGS_OTHER_CURRENT': 12808,
 'CNT_DRAWINGS_POS_CURRENT': 264902,
 'CNT_INSTALMENT_MATURE_CUM': 83772,
 'SK_DPD': 153355,
 'SK_DPD_DEF': 89340}

###winsorisasi

In [ ]:
col_out_cre = [
    'AMT_BALANCE',
    'AMT_DRAWINGS_ATM_CURRENT',
    'AMT_DRAWINGS_CURRENT',
    'AMT_RECEIVABLE_PRINCIPAL',
    'AMT_TOTAL_RECEIVABLE',
]

for c in col_out_cre:
    df_credit[c] = winsorize_series(df_credit[c])

##Feature Engineering

In [ ]:
enc_cre = AutoCountEncoder().fit_transform(df_credit)

#bureau.csv

##Data Type

In [ ]:
df_bureau.dtypes

SK_ID_CURR                  int64
SK_ID_BUREAU                int64
CREDIT_ACTIVE              object
CREDIT_CURRENCY            object
DAYS_CREDIT                 int64
CREDIT_DAY_OVERDUE          int64
DAYS_CREDIT_ENDDATE       float64
DAYS_ENDDATE_FACT         float64
AMT_CREDIT_MAX_OVERDUE    float64
CNT_CREDIT_PROLONG          int64
AMT_CREDIT_SUM            float64
AMT_CREDIT_SUM_DEBT       float64
AMT_CREDIT_SUM_LIMIT      float64
AMT_CREDIT_SUM_OVERDUE    float64
CREDIT_TYPE                object
DAYS_CREDIT_UPDATE          int64
AMT_ANNUITY               float64
dtype: object

In [ ]:
df_bureau.dtypes.astype(str).value_counts()

float64    8
int64      6
object     3
Name: count, dtype: int64

In [ ]:
obj_bureau = df_bureau.select_dtypes(include=['object']).columns
for col in obj_bureau:
    df_bureau[col] = df_bureau[col].astype('category')

##Noise

In [ ]:
df_bureau.describe()

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
count,1.716428e+06,1.716428e+06,1.716428e+06,1.716428e+06,1.610875e+06,1.082775e+06,5.919400e+05,1.716428e+06,1.716415e+06,1.458759e+06,1.124648e+06,1.716428e+06,1.716428e+06,4.896370e+05
mean,2.782149e+05,5.924434e+06,-1.142108e+03,8.181666e-01,5.105174e+02,-1.017437e+03,3.825418e+03,6.410406e-03,3.549946e+05,1.370851e+05,6.229515e+03,3.791276e+01,-5.937483e+02,1.571276e+04
std,1.029386e+05,5.322657e+05,7.951649e+02,3.654443e+01,4.994220e+03,7.140106e+02,2.060316e+05,9.622391e-02,1.149811e+06,6.774011e+05,4.503203e+04,5.937650e+03,7.207473e+02,3.258269e+05
min,1.000010e+05,5.000000e+06,-2.922000e+03,0.000000e+00,-4.206000e+04,-4.202300e+04,0.000000e+00,0.000000e+00,0.000000e+00,-4.705600e+06,-5.864061e+05,0.000000e+00,-4.194700e+04,0.000000e+00
25%,1.888668e+05,5.463954e+06,-1.666000e+03,0.000000e+00,-1.138000e+03,-1.489000e+03,0.000000e+00,0.000000e+00,5.130000e+04,0.000000e+00,0.000000e+00,0.000000e+00,-9.080000e+02,0.000000e+00
50%,2.780550e+05,5.926304e+06,-9.870000e+02,0.000000e+00,-3.300000e+02,-8.970000e+02,0.000000e+00,0.000000e+00,1.255185e+05,0.000000e+00,0.000000e+00,0.000000e+00,-3.950000e+02,0.000000e+00
75%,3.674260e+05,6.385681e+06,-4.740000e+02,0.000000e+00,4.740000e+02,-4.250000e+02,0.000000e+00,0.000000e+00,3.150000e+05,4.015350e+04,0.000000e+00,0.000000e+00,-3.300000e+01,1.350000e+04
max,4.562550e+05,6.843457e+06,0.000000e+00,2.792000e+03,3.119900e+04,0.000000e+00,1.159872e+08,9.000000e+00,5.850000e+08,1.701000e+08,4.705600e+06,3.756681e+06,3.720000e+02,1.184534e+08

In [ ]:
df_bureau[df_bureau["AMT_CREDIT_SUM_LIMIT"] < 0]["AMT_CREDIT_SUM_LIMIT"].value_counts()

AMT_CREDIT_SUM_LIMIT
-168.165       1
-5779.440      1
-110293.605    1
-11413.260     1
-1352.385      1
              ..
-6567.615      1
-18867.555     1
-1416.060      1
-316391.895    1
-15467.760     1
Name: count, Length: 351, dtype: int64

In [ ]:
cols = ["AMT_CREDIT_SUM_DEBT", "AMT_CREDIT_SUM_LIMIT"]
df_bureau = df_bureau[(df_bureau[cols] >= 0).all(axis=1)]

##Missing Value

In [ ]:
(df_bureau.isnull().sum()/len(df_bureau)*100).sort_values(ascending=False)

AMT_ANNUITY               73.032653
AMT_CREDIT_MAX_OVERDUE    55.514488
DAYS_ENDDATE_FACT         40.251161
DAYS_CREDIT_ENDDATE        5.351866
SK_ID_CURR                 0.000000
DAYS_CREDIT                0.000000
CREDIT_CURRENCY            0.000000
CREDIT_ACTIVE              0.000000
SK_ID_BUREAU               0.000000
CREDIT_DAY_OVERDUE         0.000000
CNT_CREDIT_PROLONG         0.000000
AMT_CREDIT_SUM_DEBT        0.000000
AMT_CREDIT_SUM             0.000000
AMT_CREDIT_SUM_LIMIT       0.000000
AMT_CREDIT_SUM_OVERDUE     0.000000
CREDIT_TYPE                0.000000
DAYS_CREDIT_UPDATE         0.000000
dtype: float64

In [ ]:
df_bureau = df_bureau.drop(columns=['AMT_CREDIT_SUM_OVERDUE', 'AMT_CREDIT_MAX_OVERDUE'])

In [ ]:
#mengisi mv kolom tipe float dengan median
num_cols = df_bureau.select_dtypes(include=['float','integer']).columns
df_bureau[num_cols] = df_bureau[num_cols].fillna(df_bureau[num_cols].median())

##Outlier

In [ ]:
find_outliers(df_bureau)

{'SK_ID_CURR': 0,
 'SK_ID_BUREAU': 0,
 'DAYS_CREDIT': 0,
 'CREDIT_DAY_OVERDUE': 2590,
 'DAYS_CREDIT_ENDDATE': 42769,
 'DAYS_ENDDATE_FACT': 243423,
 'CNT_CREDIT_PROLONG': 5955,
 'AMT_CREDIT_SUM': 132123,
 'AMT_CREDIT_SUM_DEBT': 198547,
 'AMT_CREDIT_SUM_LIMIT': 65637,
 'DAYS_CREDIT_UPDATE': 61381,
 'AMT_ANNUITY': 300896}

###winsorisasi

In [ ]:
col_out_bur = [
    'CREDIT_DAY_OVERDUE',
    'DAYS_CREDIT_ENDDATE',
    'DAYS_ENDDATE_FACT',
    'CNT_CREDIT_PROLONG',
    'AMT_CREDIT_SUM',
    'AMT_CREDIT_SUM_DEBT',
    'AMT_CREDIT_SUM_LIMIT',
    'DAYS_CREDIT_UPDATE',
    'AMT_ANNUITY'
]

for c in col_out_bur:
    df_bureau[c] = winsorize_series(df_bureau[c])

##Feature Engineering

In [ ]:
enc_bur = AutoCountEncoder().fit_transform(df_bureau)

#bureau_balance.csv

##Data Type

In [ ]:
df_bureau_balance.dtypes

SK_ID_BUREAU       int64
MONTHS_BALANCE     int64
STATUS            object
dtype: object

In [ ]:
df_bureau_balance['STATUS']=df_bureau_balance['STATUS'].astype('category')

##Noise

In [ ]:
df_bureau_balance.describe()

       SK_ID_BUREAU  MONTHS_BALANCE
count  2.729992e+07    2.729992e+07
mean   6.036297e+06   -3.074169e+01
std    4.923489e+05    2.386451e+01
min    5.001709e+06   -9.600000e+01
25%    5.730933e+06   -4.600000e+01
50%    6.070821e+06   -2.500000e+01
75%    6.431951e+06   -1.100000e+01
max    6.842888e+06    0.000000e+00

##Missing Value

In [ ]:
(df_bureau_balance.isnull().sum()/len(df_bureau_balance)*100).sort_values(ascending=False)

SK_ID_BUREAU      0.0
MONTHS_BALANCE    0.0
STATUS            0.0
dtype: float64

##Outliers

In [ ]:
find_outliers(df_bureau_balance)

{'SK_ID_BUREAU': 0, 'MONTHS_BALANCE': 0}

##Feature Engineering

In [ ]:
enc_bur_bal = AutoCountEncoder().fit_transform(df_bureau_balance)

#POSH_CASH_balance.csv

##Data Type

In [ ]:
df_pos.dtypes

SK_ID_PREV                 int64
SK_ID_CURR                 int64
MONTHS_BALANCE             int64
CNT_INSTALMENT           float64
CNT_INSTALMENT_FUTURE    float64
NAME_CONTRACT_STATUS      object
SK_DPD                     int64
SK_DPD_DEF                 int64
dtype: object

In [ ]:
df_pos['NAME_CONTRACT_STATUS'].unique()

array(['Active', 'Completed', 'Signed', 'Approved',
       'Returned to the store', 'Demand', 'Canceled', 'XNA',
       'Amortized debt'], dtype=object)

In [ ]:
df_pos['NAME_CONTRACT_STATUS'] = df_pos['NAME_CONTRACT_STATUS'].astype('category')

##Noise

In [ ]:
df_pos.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,SK_DPD,SK_DPD_DEF
count,1.000136e+07,1.000136e+07,1.000136e+07,9.975287e+06,9.975271e+06,1.000136e+07,1.000136e+07
mean,1.903217e+06,2.784039e+05,-3.501259e+01,1.708965e+01,1.048384e+01,1.160693e+01,6.544684e-01
std,5.358465e+05,1.027637e+05,2.606657e+01,1.199506e+01,1.110906e+01,1.327140e+02,3.276249e+01
min,1.000001e+06,1.000010e+05,-9.600000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.434405e+06,1.895500e+05,-5.400000e+01,1.000000e+01,3.000000e+00,0.000000e+00,0.000000e+00
50%,1.896565e+06,2.786540e+05,-2.800000e+01,1.200000e+01,7.000000e+00,0.000000e+00,0.000000e+00
75%,2.368963e+06,3.674290e+05,-1.300000e+01,2.400000e+01,1.400000e+01,0.000000e+00,0.000000e+00
max,2.843499e+06,4.562550e+05,-1.000000e+00,9.200000e+01,8.500000e+01,4.231000e+03,3.595000e+03

##Missing Value

In [ ]:
(df_pos.isnull().sum()/len(df_pos)*100).sort_values(ascending=False)

CNT_INSTALMENT_FUTURE    0.260835
CNT_INSTALMENT           0.260675
SK_ID_CURR               0.000000
SK_ID_PREV               0.000000
MONTHS_BALANCE           0.000000
NAME_CONTRACT_STATUS     0.000000
SK_DPD                   0.000000
SK_DPD_DEF               0.000000
dtype: float64

In [ ]:
#mengisi mv kolom tipe float dengan median
num_cols = df_pos.select_dtypes(include=['float','integer']).columns
df_pos[num_cols] = df_pos[num_cols].fillna(df_pos[num_cols].median())

##Outlier

In [ ]:
find_outliers(df_pos)

{'SK_ID_PREV': 0,
 'SK_ID_CURR': 0,
 'MONTHS_BALANCE': 0,
 'CNT_INSTALMENT': 498724,
 'CNT_INSTALMENT_FUTURE': 694783,
 'SK_DPD': 295227,
 'SK_DPD_DEF': 113969}

###winsorisasi

In [ ]:
col_out_pos = [
    'CNT_INSTALMENT',
    'CNT_INSTALMENT_FUTURE',
    'SK_DPD',
    'SK_DPD_DEF'
]

for c in col_out_pos:
    df_pos[c] = winsorize_series(df_pos[c])

##Feature Engineering

In [ ]:
enc_pos = AutoCountEncoder().fit_transform(df_pos)

#installment.csv

##Data Type

In [ ]:
df_inst.dtypes

SK_ID_PREV                  int64
SK_ID_CURR                  int64
NUM_INSTALMENT_VERSION    float64
NUM_INSTALMENT_NUMBER       int64
DAYS_INSTALMENT           float64
DAYS_ENTRY_PAYMENT        float64
AMT_INSTALMENT            float64
AMT_PAYMENT               float64
dtype: object

##Noise

In [ ]:
df_inst.describe()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
count,1.360540e+07,1.360540e+07,1.360540e+07,1.360540e+07,1.360540e+07,1.360250e+07,1.360540e+07,1.360250e+07
mean,1.903365e+06,2.784449e+05,8.566373e-01,1.887090e+01,-1.042270e+03,-1.051114e+03,1.705091e+04,1.723822e+04
std,5.362029e+05,1.027183e+05,1.035216e+00,2.666407e+01,8.009463e+02,8.005859e+02,5.057025e+04,5.473578e+04
min,1.000001e+06,1.000010e+05,0.000000e+00,1.000000e+00,-2.922000e+03,-4.921000e+03,0.000000e+00,0.000000e+00
25%,1.434191e+06,1.896390e+05,0.000000e+00,4.000000e+00,-1.654000e+03,-1.662000e+03,4.226085e+03,3.398265e+03
50%,1.896520e+06,2.786850e+05,1.000000e+00,8.000000e+00,-8.180000e+02,-8.270000e+02,8.884080e+03,8.125515e+03
75%,2.369094e+06,3.675300e+05,1.000000e+00,1.900000e+01,-3.610000e+02,-3.700000e+02,1.671021e+04,1.610842e+04
max,2.843499e+06,4.562550e+05,1.780000e+02,2.770000e+02,-1.000000e+00,-1.000000e+00,3.771488e+06,3.771488e+06

##Missing Value

In [ ]:
(df_inst.isnull().sum()/len(df_inst)*100).sort_values(ascending=False)

AMT_PAYMENT               0.021352
DAYS_ENTRY_PAYMENT        0.021352
SK_ID_PREV                0.000000
SK_ID_CURR                0.000000
NUM_INSTALMENT_NUMBER     0.000000
NUM_INSTALMENT_VERSION    0.000000
DAYS_INSTALMENT           0.000000
AMT_INSTALMENT            0.000000
dtype: float64

In [ ]:
mv_ins = ['AMT_PAYMENT', 'DAYS_ENTRY_PAYMENT']
df_inst[mv_ins] = df_inst[mv_ins].fillna(df_inst[mv_ins].median())

##Outlier

In [ ]:
find_outliers(df_inst)

{'SK_ID_PREV': 0,
 'SK_ID_CURR': 0,
 'NUM_INSTALMENT_VERSION': 417616,
 'NUM_INSTALMENT_NUMBER': 1886320,
 'DAYS_INSTALMENT': 0,
 'DAYS_ENTRY_PAYMENT': 1,
 'AMT_INSTALMENT': 1120800,
 'AMT_PAYMENT': 1130428}

###winsorisasi

In [ ]:
col_out_inst = [
    'NUM_INSTALMENT_VERSION',
    'NUM_INSTALMENT_NUMBER',
    'DAYS_ENTRY_PAYMENT',
    'AMT_INSTALMENT',
    'AMT_PAYMENT',
]

for c in col_out_inst:
    df_inst[c] = winsorize_series(df_inst[c])

##Feature Engineering

In [ ]:
enc_inst = AutoCountEncoder().fit_transform(df_inst)

#sample.csv

##Data Type

In [ ]:
df_sample.dtypes

SK_ID_CURR      int64
TARGET        float64
dtype: object

In [ ]:
df_sample

       SK_ID_CURR  TARGET
0          100001     0.5
1          100005     0.5
2          100013     0.5
3          100028     0.5
4          100038     0.5
...           ...     ...
48739      456221     0.5
48740      456222     0.5
48741      456223     0.5
48742      456224     0.5
48743      456250     0.5

[48744 rows x 2 columns]

##Noise

In [ ]:
df_sample.describe()

          SK_ID_CURR   TARGET
count   48744.000000  48744.0
mean   277796.676350      0.5
std    103169.547296      0.0
min    100001.000000      0.5
25%    188557.750000      0.5
50%    277549.000000      0.5
75%    367555.500000      0.5
max    456250.000000      0.5

##Missing Value

In [ ]:
(df_sample.isnull().sum()/len(df_sample)*100).sort_values(ascending=False)

SK_ID_CURR    0.0
TARGET        0.0
dtype: float64

##Outlier

In [ ]:
find_outliers(df_sample)

{'SK_ID_CURR': 0, 'TARGET': 0}

In [ ]:
enc_app_train.to_csv('clean_app_train.csv', index=False)
enc_app_test.to_csv('clean_app_test.csv', index=False)
enc_pre_app.to_csv('clean_pre_app.csv', index=False)
enc_cre.to_csv('clean_cre.csv', index=False)
enc_bur.to_csv('clean_bur.csv', index=False)
enc_bur_bal.to_csv('clean_bur_bal.csv', index=False)
enc_pos.to_csv('clean_pos.csv', index=False)
enc_inst.to_csv('clean_inst.csv', index=False)
df_sample.to_csv('clean_sample.csv', index=False)